services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    ports:
      - "8050:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../backend/Dockerfile-dev
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:80"
    environment:
      - APP_NAME=IntraCore
      - APP_ENV=local
      - APP_KEY="base64:PX2orSE2KW6rqy5wZKx3cJJBCzH6LVhgEjHc2lXgMAU="
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=intracore
      - DB_USERNAME=intracore
      - DB_PASSWORD=secret
      - FRONTEND_URL=http://localhost:8050
      - REDIS_HOST=redis
      # Mail Configuration
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=noreply@intracore.com
      - MAIL_FROM_NAME=IntraCore
      - ONESIGNAL_APP_ID=8f98d172-c3be-458b-b393-77fe637539ed
      - ONESIGNAL_REST_API_KEY=os_v2_app_r6mnc4wdxzcyxm4to77gg5jz5vwmp3aubtfebyvramo25rjfakmrvw4aifikwxs3damz5ry7lltyg74cqp3mnjref5nrbm3cphyizxa
      - ONESIGNAL_REST_API_URL=https://api.onesignal.com
    depends_on:
      - db
      - redis     
      - mailhog

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=intracore
      - MYSQL_USER=intracore
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server

volumes:
  mysql_data:
  redis_data: 